### ISSUE TITLE
Having issues opening (local developement)

### ISSUE THREAD

**Issue by Ciphr7** [frankdiox/OnsenUI-Todo-App#4]
I get these errors when i try to run the index file locally.

internal.js:147 XMLHttpRequest cannot load file:///C:/app/Todo-App-Onsen/html/menu.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
load @ ons-splitter-side.js:686
(anonymous) @ ons-splitter-side.js:530
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
ready @ ons-splitter-side.js:42
_updatePage @ ons-splitter-side.js:530
_update @ ons-splitter-side.js:487
(anonymous) @ ons-splitter-side.js:469
(anonymous) @ ons-splitter-side.js:469
(anonymous) @ content-ready.js:41
consumeQueue @ content-ready.js:41
contentReady @ content-ready.js:48
attachedCallback @ ons-splitter-side.js:468
(anonymous) @ index.js:438
run @ index.js:432
Promise resolved (async)
(anonymous) @ internal.js:131
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
(anonymous) @ index.js:445
_pushPage @ index.js:466
pushPage @ index.js:445
(anonymous) @ index.js:242
ready @ index.js:53
attachedCallback @ index.js:240
internal.js:145 Uncaught Error: The page is not found: html/menu.html
    at XMLHttpRequest.xhr.onerror (internal.js:145)
    at internal.js:147
    at internal.js:132
    at setImmediate.js:48
    at runIfPresent (setImmediate.js:67)
    at onGlobalMessage (setImmediate.js:113)
xhr.onerror @ internal.js:145
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
XMLHttpRequest.send (async)
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
load @ ons-splitter-side.js:686
(anonymous) @ ons-splitter-side.js:530
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
ready @ ons-splitter-side.js:42
_updatePage @ ons-splitter-side.js:530
_update @ ons-splitter-side.js:487
(anonymous) @ ons-splitter-side.js:469
(anonymous) @ ons-splitter-side.js:469
(anonymous) @ content-ready.js:41
consumeQueue @ content-ready.js:41
contentReady @ content-ready.js:48
attachedCallback @ ons-splitter-side.js:468
(anonymous) @ index.js:438
run @ index.js:432
Promise resolved (async)
(anonymous) @ internal.js:131
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
(anonymous) @ index.js:445
_pushPage @ index.js:466
pushPage @ index.js:445
(anonymous) @ index.js:242
ready @ index.js:53
attachedCallback @ index.js:240
internal.js:147 XMLHttpRequest cannot load file:///C:/app/Todo-App-Onsen/html/pending_tasks.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
_createPageElement @ ons-tab.js:326
_loadPageElement @ ons-tab.js:295
_ret.v @ index.js:527
(anonymous) @ index.js:526
setActiveTab @ index.js:493
(anonymous) @ ons-tab.js:357
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ ons-tab.js:357
ready @ index.js:46
(anonymous) @ ons-tab.js:356
(anonymous) @ ons-tab.js:353
(anonymous) @ content-ready.js:41
consumeQueue @ content-ready.js:41
contentReady @ content-ready.js:48
attachedCallback @ ons-tab.js:343
(anonymous) @ ons-splitter-content.js:140
link @ ons-splitter-content.js:39
(anonymous) @ ons-splitter-content.js:136
(anonymous) @ ons-splitter-content.js:135
Promise resolved (async)
(anonymous) @ internal.js:131
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
load @ ons-splitter-content.js:135
(anonymous) @ ons-splitter-content.js:100
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
ready @ ons-splitter-content.js:29
attributeChangedCallback @ ons-splitter-content.js:100
attachedCallback @ ons-splitter-content.js:93
(anonymous) @ index.js:438
run @ index.js:432
internal.js:145 Uncaught Error: The page is not found: html/pending_tasks.html
    at XMLHttpRequest.xhr.onerror (internal.js:145)
    at internal.js:147
    at internal.js:132
    at setImmediate.js:48
    at runIfPresent (setImmediate.js:67)
    at onGlobalMessage (setImmediate.js:113)
xhr.onerror @ internal.js:145
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
XMLHttpRequest.send (async)
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
_createPageElement @ ons-tab.js:326
_loadPageElement @ ons-tab.js:295
_ret.v @ index.js:527
(anonymous) @ index.js:526
setActiveTab @ index.js:493
(anonymous) @ ons-tab.js:357
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ ons-tab.js:357
ready @ index.js:46
(anonymous) @ ons-tab.js:356
(anonymous) @ ons-tab.js:353
(anonymous) @ content-ready.js:41
consumeQueue @ content-ready.js:41
contentReady @ content-ready.js:48
attachedCallback @ ons-tab.js:343
(anonymous) @ ons-splitter-content.js:140
link @ ons-splitter-content.js:39
(anonymous) @ ons-splitter-content.js:136
(anonymous) @ ons-splitter-content.js:135
Promise resolved (async)
(anonymous) @ internal.js:131
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
load @ ons-splitter-content.js:135
(anonymous) @ ons-splitter-content.js:100
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
ready @ ons-splitter-content.js:29
attributeChangedCallback @ ons-splitter-content.js:100
attachedCallback @ ons-splitter-content.js:93
(anonymous) @ index.js:438
run @ index.js:432
internal.js:147 XMLHttpRequest cannot load file:///C:/app/Todo-App-Onsen/html/completed_tasks.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
(anonymous) @ internal.js:147
(anonymous) @ internal.js:132
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
_createPageElement @ ons-tab.js:326
(anonymous) @ ons-tab.js:363
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ ons-tab.js:361
ready @ index.js:46
(anonymous) @ ons-tab.js:360
(anonymous) @ content-ready.js:41
consumeQueue @ content-ready.js:41
contentReady @ content-ready.js:48
attachedCallback @ ons-tab.js:343
(anonymous) @ ons-splitter-content.js:140
link @ ons-splitter-content.js:39
(anonymous) @ ons-splitter-content.js:136
(anonymous) @ ons-splitter-content.js:135
Promise resolved (async)
(anonymous) @ internal.js:131
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
(anonymous) @ internal.js:126
internal.getTemplateHTMLAsync @ internal.js:125
getPage @ internal.js:165
internal.getPageHTMLAsync @ internal.js:181
load @ ons-splitter-content.js:135
(anonymous) @ ons-splitter-content.js:100
(anonymous) @ setImmediate.js:48
runIfPresent @ setImmediate.js:67
onGlobalMessage @ setImmediate.js:113
postMessage (async)
setImmediate @ setImmediate.js:125
ready @ ons-splitter-content.js:29
attributeChangedCallback @ ons-splitter-content.js:100
attachedCallback @ ons-splitter-content.js:93
(anonymous) @ index.js:438
run @ index.js:432
internal.js:145 Uncaught Error: The page is not found: html/completed_tasks.html
    at XMLHttpRequest.xhr.onerror (internal.js:145)
    at internal.js:147
    at internal.js:132
    at setImmediate.js:48
    at runIfPresent (setImmediate.js:67)
    at onGlobalMessage (setImmediate.js:113)

**Comment by frandiox** [comment]
@Cipher7z You cannot simply open `index.html` in a browser. The whole project must be served. You can use any server you want, like [`http-server`](https://www.npmjs.com/package/http-server).

**Comment by Ciphr7** [comment]
@frandiox Thanks for the tip unfortunately i'm still lost. I have installed http-server then ran " http-server C:\app\OnsenUI-Todo-App-master\" where all content found in the repository are found. Still the app does not run. Using http-server is new to me so i'm sure i'm making a nub mistake.

**Comment by frandiox** [comment]
@Cipher7z Try:
```
cd C:\app\OnsenUI-Todo-App-master
http-server . -o -c-1
```

**Comment by Ciphr7** [comment]
That worked, off to the races I go! Thank you so much Fran!
