### ISSUE TITLE
App not working when running from local machine

### ISSUE THREAD

**Issue by humanitiesclinic** [frankdiox/OnsenUI-Todo-App#7]
Hi,

I tried downloading the code, and running it without modifying anything. I opened index.html directly like a file in my browser. The controls don't work. I can see the UI like "Pending", "Completed" tab, and "New". But when I click on "New" nothing happens. When I click on the Menu icon, nothing happens as well. Am I doing something wrong? Can the app be opened directly in a browser?

**Comment by frandiox** [comment]
@humanitiesclinic You need to serve the app with a tool like [http-server](https://www.npmjs.com/package/http-server).

**Comment by humanitiesclinic** [comment]
Oh I see. Can I use Cordova with this OnsenUI project? I notice it has some node modules, I am not sure how to include node modules in Cordova as of now. Is it possible?

**Comment by frandiox** [comment]
@humanitiesclinic It's supposed to work in Cordova, yes. I don't see any `node_modules` folder in the repo 🤔
